config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

  devise_for :users, controllers: { 
    registrations: "users/registrations",   
    sessions: "users/sessions", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"}

  get 'pages/index'

  get 'pages/about'

  get 'mypins' => 'pins#mypins'

  get 'pinsof/:user_id' => 'pins#pinsof'
 
 

  root 'pages#index'
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :photo, presence: { message: "es requerido!"}
	validates :name, presence: { message: "es requerido!"}
    validates :description, presence: { message: "es requerido!"}

    # un pin le pertenece a 1 usuario.
    belongs_to :user

    #un pin tiene muchas imagenes.
    #mount_uploader :avatars, AvatarUploader


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!, except: [ :index, :show ]
 
 #exigir autenticacipn
  before_filter :authenticate_user!, except: [:index, :show]
  
def pinsof
  @user_id = params[:user_id]
  @user =User.find(@user_id)
  @pins =@user.pins 
  
end

  

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    #@pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # metodo para mostrar MIS PINS. (LOS PINS DE UN USUARIO LOGUEADO.)
  def mypins
    @pins = current_user.pins
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end


end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/__pinsof.html.erb
<h1>Muestra los pins del Usuario <%= @user_id %></h1>

 
<p id="notice"><%= notice %></p>   

   <!-- iteramos los pins del usuario x.
   se comunica con el metodo pinsof del controller pins_controller.rb -->

    <% @pins.each do |pin| %>
      <div class="col-md-3">
          <div class="thumbnail">
              <p><strong><%= pin.name %></strong></p>                  
               <%= image_tag(pin.photo, class:'img-responsive') %>
              <p><%= pin.description %></p>       
                
           </div><!-- //cierra thumbnail-->
        </div>  <!-- //cierra col-md-3-->
    <% end %> 



 


app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
<% if @pin.errors.any? %>
<div id="error_explanation">

  <h2><%= pluralize(@pin.errors.count, "error") %> campos son requeridos:</h2>

  <ul>
    <% @pin.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <div class="field">
    Nombre:<br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
</div>

<div class="form-group">

  <div class="field">
    Descripcion<br>
    <%= f.text_field :description, class:'form-control' %>
  </div>
</div>

<div class="form-group">

 <div class="field">
   Foto:<br>
   <%= f.text_field :photo, class:'form-control' %>
 </div>
</div>



<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html - copia (2)-original.erb
<p id="notice"><%= notice %></p>


 
<!-- Si el usuario esta logueado, entonces muestro el boton para crear un nuevo pin-->
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path, class:'btn btn-sm btn-success' %>
<% end %>


<h1>Lista de Todos los Pins.</h1>

<!-- ITERAMOS LOS PINS DE TODOOOOOOSS LOS USUARIOS.
 (se comunica con el metodo index del controller pins_controlller.rb-->

 

<div class="container">
 <% @pins.each do |pin| %>

 <div class="col-md-3">
  <div class="thumbnail">
    <p><strong><%= pin.name %></strong></p>
    <%= image_tag(pin.photo, class:'img-responsive') %>
    <p><%= pin.description %></p>
    <%= link_to 'Mostrar', pin, class:'btn btn-default btn-xs' %> 
    <% if user_signed_in? %>
    <%= link_to 'Editar', edit_pin_path(pin), class:'btn btn-info btn-xs' %>
    <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'estas seguro?' }, class:'btn btn-danger btn-xs' %> <% end %>
  </div><!-- //cierra thumbnail-->
</div>  <!-- //cierra col-md-3-->
<% end %>

</div>

<br>

 

app/views/pins/index.html - copia.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Todos los Pins.</h1>

 
    <% @pins.each do |pin| %>
      
         <%= pin.name %> 
         
         <%= image_tag(pin.photo, class: 'img-responsive') %>  
         <%= pin.description %> 
         <%= link_to 'Show', pin %> 
         <%= link_to 'Edit', edit_pin_path(pin) %> 
         <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'estas seguro?' } %> 
       
    <% end %>
   
 

<br>


<% if user_signed_in? %>

  <%= link_to 'New Pin', new_pin_path %>

<% end %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>


 
<!-- Si el usuario esta logueado, entonces muestro el boton para crear un nuevo pin-->
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path, class:'btn btn-sm btn-success' %>
<% end %>


<h1>Lista de Todos los Pins.</h1>

<!-- ITERAMOS LOS PINS DE TODOOOOOOSS LOS USUARIOS.
 (se comunica con el metodo index del controller pins_controlller.rb-->

 

<div class="container">
 <% @pins.each do |pin| %>

 <div class="col-md-3" >
  <div class="thumbnail">
    <p><strong><%= pin.name %></strong></p>
    <%= image_tag(pin.photo, class:'img-responsive') %>
    <p><%= pin.description %></p>
    <%= link_to 'Mostrar', pin, class:'btn btn-default btn-xs' %> 
    <% if user_signed_in? %>
    <%= link_to 'Editar', edit_pin_path(pin), class:'btn btn-info btn-xs' %>
    <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'estas seguro?' }, class:'btn btn-danger btn-xs' %> <% end %>
  </div><!-- //cierra thumbnail-->
</div>  <!-- //cierra col-md-3-->
<% end %>

</div>

<br>

 

app/views/pins/mypins.html.erb

<% if user_signed_in? %>

    <%= link_to 'New Pin', new_pin_path, class:'btn btn-success' %>

<% end %>

<h1>Mis Pins </h1>

<p id="notice"><%= notice %></p>

   

   <!-- iteramos los pins del usuario ACTUAL.
   se comunica con el metodo mypins del controller pins_controller.rb -->

    <% @pins.each do |pin| %>



      <div class="col-md-3">

          <div class="thumbnail">

              <p><strong><%= pin.name %></strong></p>
                  
               <%= image_tag(pin.photo, class:'img-responsive') %>

              <p><%= pin.description %></p>

          
                 <%= link_to 'Mostrar', pin, class:'btn btn-default btn-xs' %> 

                 <%= link_to 'Editar', edit_pin_path(pin), class:'btn btn-info btn-xs' %>

                 <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'estas seguro?' }, class:'btn btn-danger btn-xs' %> 
           </div><!-- //cierra thumbnail-->

        </div>  <!-- //cierra col-md-3-->
 

    <% end %>
 
<br>



 


app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/pinsof.html.erb
 <h1>Pins del usario <%= @user_id %></h1>

 <% @pins.each do |pin| %>

      <div class="col-md-3">

          <div class="thumbnail">

              <p><strong><%= pin.name %></strong></p>
                  
               <%= image_tag(pin.photo, class:'img-responsive') %>

              <p><%= pin.description %></p>

                <%= link_to 'Mostrar', pin, class:'btn btn-default btn-xs' %> 
 
                  
           </div><!-- //cierra thumbnail-->

        </div>  <!-- //cierra col-md-3-->
 

    <% end %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
<p>
   
    <h2><%= @pin.name %></h2>
</p>
<p>
   
	 <img src="<%= @pin.photo %>" alt="<%= @pin.name %>" class="img-responsive">
 
</p>

<p class="text-left">
   <%= @pin.description %>
</p>



</div>

<%= link_to 'Edit', edit_pin_path(@pin), class:'btn btn-default' %> |
<%= link_to 'Back', pins_path, class:'btn btn-default' %>