config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

  devise_for :users, controllers: { 
    registrations: "users/registrations",   
    sessions: "users/sessions", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"}

  get 'pages/index'

  get 'pages/about'

  get 'mypins' => 'pins#mypins'

  get 'pinsof/:user_id' => 'pins#pinsof'
 
 

  root 'pages#index'
  

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
 <!-- aqui solo cargamos cosas que iran dentro del body-->


 <div class="jumbotron">
 	<p class="notice" style="color:white;font-weight:bold"><%= notice %></p>

 	<div class="container">
 		<div class="col-lg-12">
 			<p>
				<!--Si el usuario esta logueado entonces que muestre la imagen -->
				<% if user_signed_in? %>
	 			<img src="<%= current_user.image %>" alt="" class="img-responsive">
				<% end  %>

 			</p>

 			<h2>
 				
 				Red <span class="text-info">musical urbana</span> que surge de la necesidad de recopilar extractos de músicos que llevan su arte a las <span class="text-info">calles</span> y escenarios del <span class="text-info">mundo</span>. 
 				
 			</h2>		
 			<a class="btn btn-sm btn-default" role="button" href="#">Leer más »</a>

 		</div>
 	</div><!-- //fin de container-->
 </div><!-- //fin de Jumbotron-->

 <div class="container">
 	<div class="container marketing">

 		<!-- Three columns of text below the carousel -->
 		<div class="row">
 			<div class="col-lg-4">
 				<img style="width: 140px; height: 140px;" alt="Generic placeholder image" src="https://i.ytimg.com/vi/nZhZQx-5LrQ/mqdefault.jpg" class="img-circle">
 				<h2>CC: beatbox chileno</h2>
 				<p>

 					
 					
 					Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
 					<p><a role="button" href="<%= pages_index_path %>" class="btn btn-default">Descubrir »</a></p>
 				</div><!-- /.col-lg-4 -->


 				<div class="col-lg-4">
 					<img style="width: 140px; height: 140px;" alt="Generic placeholder image" src="https://i.ytimg.com/vi/4ridVan2qsM/mqdefault.jpg" class="img-circle">
 					<h2>CC: Violin and Didgeridoo</h2>
 					<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
 					<p><a role="button" href="<%= pages_index_path %>" class="btn btn-default">Descubrir »</a></p>
 				</div><!-- /.col-lg-4 -->


 				<div class="col-lg-4">
 					<img style="width: 140px; height: 140px;" alt="Generic placeholder image" src="https://i.ytimg.com/vi/1zBqnGe71JA/mqdefault.jpg" class="img-circle">
 					<h2>CC: Romina, Acordeón</h2>
 					<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
 					<p><a role="button" href="<%= pages_index_path %>" class="btn btn-default">Descubrir »</a></p>
 				</div><!-- /.col-lg-4 -->
 			</div><!-- /.row -->


 			<!-- START THE FEATURETTES -->

 			<div class="row">
 				<div class="col-lg-12">
 					<div class="page-header">
 						<h1 id="type">Nuestras influencias musicales...</h1>
 					</div>
 				</div>
 			</div>

 			<div class="row featurette">
 				<div class="col-md-7">
 					<h2 class="featurette-heading">Banda Mala Hierba. <span class="text-muted">Me invitaron a un día de ensayo.</span></h2>
 					<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
 				</div>
 				<div class="col-md-5">
 					<img alt="500x500" data-src="holder.js/500x500/auto" class="featurette-image img-responsive" src="https://i.ytimg.com/vi/QTOFlgWVhQY/0.jpg">
 				</div>
 			</div>

 			<div class="row">
 				<div class="col-lg-12">
 					<div class="page-header">
 						<h1 id="type">Músicos en las Calles del Mundo!</h1>

 					</div>
 				</div>
 			</div>

 			<div class="row featurette">
 				<div class="col-md-5">
 					<img alt="500x500" data-src="holder.js/500x500/auto" class="featurette-image img-responsive" src="https://i.ytimg.com/vi/lMpZGAUGk8w/0.jpg">
 				</div>
 				<div class="col-md-7">
 					<h2 class="featurette-heading">Cueca chora en Lastarria. <span class="text-muted">Pongase a bailar hace bien.</span></h2>
 					<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
 				</div>
 			</div>

 			<div class="row">
 				<div class="col-lg-12">
 					<div class="page-header">
 						<h1 id="type">Oda al...Saxofón</h1>

 					</div>
 				</div>
 			</div>

 			<div class="row featurette">
 				<div class="col-md-7">
 					<h2 class="featurette-heading">Saxofón y el Jazz. <span class="text-muted">Instrumentos de viento y otras hierbas.</span></h2>
 					<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
 				</div>
 				<div class="col-md-5">
 					<img alt="500x500" data-src="holder.js/500x500/auto" class="featurette-image img-responsive" src=" https://i.ytimg.com/vi/HIONSDlaOic/0.jpg">
 				</div>
 			</div>

 			<hr class="featurette-divider">

 			<!-- /END THE FEATURETTES -->



 		</div>

 	</div>