config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

  devise_for :users, controllers: { 
    registrations: "users/registrations",   
    sessions: "users/sessions", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"}

  get 'pages/index'

  get 'pages/about'

  get 'mypins' => 'pins#mypins'

  get 'pinsof/:user_id' => 'pins#pinsof'
 
 

  root 'pages#index'
  

end

app/views/layouts/_footer.html.erb
 <!-- FOOTER -->
      <div class="clearfix"></div>

	<footer class="text-center">
	    <div class="container">
        <p class="pull-right"><a href="#">Subir</a></p>
        <p>&copy; 2014 ConciertosComentados · <a href="#">Privacy</a> · <a href="#">Todos los derechos compartidos</a></p>
        </div>
   
   </footer>

app/views/layouts/_navbar.html.erb
<!-- BARRA NAVEGACION PRINCIPAL SUPERIOR-->
<nav class="navbar navbar-default " role="navigation" style="margin-bottom: 0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">STREET MUSIC WALL</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

          
         <li><a href="<%= pins_path %>">Ver Todos los Pins</a></li>
        
        <!-- Si el usuario NO esta logueado, mostrar Ingreso y el registros-->
        <% if current_user.nil? %>  
           
        <li><a href="<%= new_user_session_path %>">Ingreso</a> </li>
         <li><a href="<%= new_user_registration_path %>">Registro</a> </li>
       
        <% else %>
         
         <li><a href="<%= mypins_path %>">Ver Mis Pins!</a></li>        
           
        <li>
        <a href="<%= mypins_path %>">
         <% if user_signed_in? %>
               Hola, <%= current_user.name %>,  <%= current_user.email %>               
          <% end %>
        </a>
        </li>
 

        <li><a href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a></li>
        

        <% end %>
 
 
      </ul>
      
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- //BARRA NAVEGACION PRINCIPAL SUPERIOR-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STREET MUSIC WALL</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
 
<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.2.2/masonry.pkgd.min.js"></script>

<!-- //analytics -->

</head>
<body>

<!-- AQUI PNER UNA VISTA PARCIAL DEL _NAVBAR.-->

<!-- barra de navegacion parcial que se carga en _navbar.html.erb -->

<%= render 'layouts/navbar' %>

<%= render 'shared/facebook_sdk' %>

<%= yield %>



<%= render 'layouts/footer' %>

 

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>


<p class="alert"><%= alert %></p>
</body>
</html>